{% set version = "0.18" %}

package:
  name: perl-autovivification
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/V/VP/VPIT/autovivification-{{ version }}.tar.gz
  sha256: 2d99975685242980d0a9904f639144c059d6ece15899efde4acb742d3253f105

build:
  script: |
    perl Makefile.PL INSTALLDIRS=vendor
    make
    make test
    make install
  skip: true  # [win]
  number: 0
  run_exports:
    weak:
      - perl-autovivification ={{ version }}

requirements:
  build:
    - make
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - autovivification

about:
  home: https://metacpan.org/pod/autovivification
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
  summary: Lexically disable autovivification.

extra:
  recipe-maintainers:
    - njzjz
